# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-23 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dummy_attribute', models.CharField(default='foo', max_length=100)),
            ],
        ),
    ]
